---

stack_name: "srawi-servers"

#aws_key_name: "srawikey"

server_name1: "server1.srawi.com"
server_name2: "server2.srawi.com"

aws_instancetype: "t2.medium"

subnet1: subnet-0adff8fa66d007b07
subnet2: subnet-0e4dd303855f01018

ebs_key: "2b1170dd-b829-4131-a244-ad6905109a12"
hosted_zone: Z0595769M0U5QKSNS415 # dev.maxomni.com
vpc_id: vpc-04ac5765d68f5872f

#Disks to attach to instance
disks:
  - name: "root_volume"
    type: "gp2"
    size: "30"
    device_name: "/dev/sda1"