---

stack_name: "myservers"

aws_key_name: "srawikey"

server_name1: "server1.srawi.com"
server_name2: "server2.srawi.com"

aws_instancetype: "t2.medium"

subnet1: subnet-0f29ba3d25a0ffe50
subnet2: subnet-0927e9efdfa56f9e2

ebs_key: "ff01e1f8-edfa-44d6-b511-3fc07445765c"
hosted_zone: Z0595769M0U5QKSNS415 # dev.maxomni.com
vpc_id: vpc-08bc22c74b865ad81

#Disks to attach to instance
disks:
  - name: "root_volume"
    type: "gp2"
    size: "50"
    device_name: "/dev/sda1"